# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, lang: float=None, latd: float=None):  # noqa: E501
        """Body1 - a model defined in Swagger

        :param name: The name of this Body1.  # noqa: E501
        :type name: str
        :param lang: The lang of this Body1.  # noqa: E501
        :type lang: float
        :param latd: The latd of this Body1.  # noqa: E501
        :type latd: float
        """
        self.swagger_types = {
            'name': str,
            'lang': float,
            'latd': float
        }

        self.attribute_map = {
            'name': 'name',
            'lang': 'lang',
            'latd': 'latd'
        }

        self._name = name
        self._lang = lang
        self._latd = latd

    @classmethod
    def from_dict(cls, dikt) -> 'Body1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_1 of this Body1.  # noqa: E501
        :rtype: Body1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Body1.


        :return: The name of this Body1.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Body1.


        :param name: The name of this Body1.
        :type name: str
        """

        self._name = name

    @property
    def lang(self) -> float:
        """Gets the lang of this Body1.


        :return: The lang of this Body1.
        :rtype: float
        """
        return self._lang

    @lang.setter
    def lang(self, lang: float):
        """Sets the lang of this Body1.


        :param lang: The lang of this Body1.
        :type lang: float
        """

        self._lang = lang

    @property
    def latd(self) -> float:
        """Gets the latd of this Body1.


        :return: The latd of this Body1.
        :rtype: float
        """
        return self._latd

    @latd.setter
    def latd(self, latd: float):
        """Sets the latd of this Body1.


        :param latd: The latd of this Body1.
        :type latd: float
        """

        self._latd = latd
