# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, public_id: int=None, name: str=None, lang: float=None, latd: float=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param public_id: The public_id of this Body.  # noqa: E501
        :type public_id: int
        :param name: The name of this Body.  # noqa: E501
        :type name: str
        :param lang: The lang of this Body.  # noqa: E501
        :type lang: float
        :param latd: The latd of this Body.  # noqa: E501
        :type latd: float
        """
        self.swagger_types = {
            'public_id': int,
            'name': str,
            'lang': float,
            'latd': float
        }

        self.attribute_map = {
            'public_id': 'public_id',
            'name': 'name',
            'lang': 'lang',
            'latd': 'latd'
        }

        self._public_id = public_id
        self._name = name
        self._lang = lang
        self._latd = latd

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def public_id(self) -> int:
        """Gets the public_id of this Body.


        :return: The public_id of this Body.
        :rtype: int
        """
        return self._public_id

    @public_id.setter
    def public_id(self, public_id: int):
        """Sets the public_id of this Body.


        :param public_id: The public_id of this Body.
        :type public_id: int
        """

        self._public_id = public_id

    @property
    def name(self) -> str:
        """Gets the name of this Body.


        :return: The name of this Body.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Body.


        :param name: The name of this Body.
        :type name: str
        """

        self._name = name

    @property
    def lang(self) -> float:
        """Gets the lang of this Body.


        :return: The lang of this Body.
        :rtype: float
        """
        return self._lang

    @lang.setter
    def lang(self, lang: float):
        """Sets the lang of this Body.


        :param lang: The lang of this Body.
        :type lang: float
        """

        self._lang = lang

    @property
    def latd(self) -> float:
        """Gets the latd of this Body.


        :return: The latd of this Body.
        :rtype: float
        """
        return self._latd

    @latd.setter
    def latd(self, latd: float):
        """Sets the latd of this Body.


        :param latd: The latd of this Body.
        :type latd: float
        """

        self._latd = latd
